### ISSUE TITLE
Feat: Tables

### ISSUE THREAD

**Issue by minorOffense** [Graupl/graupl#33] opened 2024-04-26 13:32 UTC
## Summary
Basic table support with the option for responsive tables (including priority columns and/or scrolling)

## Solution
table markup

Optional classes for responsiveness, row highlinghts, alternating colours, borders, etc.

Table captions and/or summary support is also required.

**Comment by NickDJM** [comment] 2024-04-26 17:52
Closing as duplicate of #24

**Closed as completed by NickDJM** 2024-04-26 17:52 UTC
Labels: enhancement
